
import { Classroom, Equipment } from './types';

export const PERIOD_TIMES: { [key: number]: string } = {
    1: '08:40–09:40',
    2: '09:40–10:40',
    3: '10:40–11:40',
    4: '12:40–13:40',
    5: '13:40–14:40',
    6: '14:50–15:50',
};

export const INITIAL_CLASSROOMS: Classroom[] = [
    // Kindergarten
    { id: 'K1ATP', program: 'Kindergarten', name_th: 'อ.1A TP', name_en: 'K.1A TP' },
    { id: 'K1BTP', program: 'Kindergarten', name_th: 'อ.1B TP', name_en: 'K.1B TP' },
    { id: 'K2ATP', program: 'Kindergarten', name_th: 'อ.2A TP', name_en: 'K.2A TP' },
    { id: 'K2BTP', program: 'Kindergarten', name_th: 'อ.2B TP', name_en: 'K.2B TP' },
    { id: 'K3ATP', program: 'Kindergarten', name_th: 'อ.3A TP', name_en: 'K.3A TP' },
    { id: 'K3BTP', program: 'Kindergarten', name_th: 'อ.3B TP', name_en: 'K.3B TP' },
    { id: 'K1AEP', program: 'Kindergarten', name_th: 'อ.1A EP', name_en: 'K.1A EP' },
    { id: 'K1BEP', program: 'Kindergarten', name_th: 'อ.1B EP', name_en: 'K.1B EP' },
    { id: 'K2AEP', program: 'Kindergarten', name_th: 'อ.2A EP', name_en: 'K.2A EP' },
    { id: 'K2BEP', program: 'Kindergarten', name_th: 'อ.2B EP', name_en: 'K.2B EP' },
    { id: 'K3AEP', program: 'Kindergarten', name_th: 'อ.3A EP', name_en: 'K.3A EP' },
    { id: 'K3BEP', program: 'Kindergarten', name_th: 'อ.3B EP', name_en: 'K.3B EP' },

    // Thai Programme
    { id: 'TP1A', program: 'Thai Programme', name_th: 'ป.1A TP', name_en: 'P.1A TP' },
    { id: 'TP1B', program: 'Thai Programme', name_th: 'ป.1B TP', name_en: 'P.1B TP' },
    { id: 'TP2A', program: 'Thai Programme', name_th: 'ป.2A TP', name_en: 'P.2A TP' },
    { id: 'TP2B', program: 'Thai Programme', name_th: 'ป.2B TP', name_en: 'P.2B TP' },
    { id: 'TP3A', program: 'Thai Programme', name_th: 'ป.3A TP', name_en: 'P.3A TP' },
    { id: 'TP3B', program: 'Thai Programme', name_th: 'ป.3B TP', name_en: 'P.3B TP' },
    { id: 'TP4A', program: 'Thai Programme', name_th: 'ป.4A TP', name_en: 'P.4A TP' },
    { id: 'TP4B', program: 'Thai Programme', name_th: 'ป.4B TP', name_en: 'P.4B TP' },
    { id: 'TP5A', program: 'Thai Programme', name_th: 'ป.5A TP', name_en: 'P.5A TP' },
    { id: 'TP5B', program: 'Thai Programme', name_th: 'ป.5B TP', name_en: 'P.5B TP' },
    { id: 'TP6A', program: 'Thai Programme', name_th: 'ป.6A TP', name_en: 'P.6A TP' },
    { id: 'TP6B', program: 'Thai Programme', name_th: 'ป.6B TP', name_en: 'P.6B TP' },
    { id: 'TM1A', program: 'Thai Programme', name_th: 'ม.1A TP', name_en: 'M.1A TP' },
    { id: 'TM1B', program: 'Thai Programme', name_th: 'ม.1B TP', name_en: 'M.1B TP' },
    { id: 'TM2A', program: 'Thai Programme', name_th: 'ม.2A TP', name_en: 'M.2A TP' },
    { id: 'TM2B', program: 'Thai Programme', name_th: 'ม.2B TP', name_en: 'M.2B TP' },
    { id: 'TM3A', program: 'Thai Programme', name_th: 'ม.3A TP', name_en: 'M.3A TP' },
    { id: 'TM3B', program: 'Thai Programme', name_th: 'ม.3B TP', name_en: 'M.3B TP' },
    { id: 'TM4A', program: 'Thai Programme', name_th: 'ม.4A TP', name_en: 'M.4A TP' },
    { id: 'TM5A', program: 'Thai Programme', name_th: 'ม.5A TP', name_en: 'M.5A TP' },
    { id: 'TM6A', program: 'Thai Programme', name_th: 'ม.6A TP', name_en: 'M.6A TP' },

    // English Programme
    { id: 'EP1A', program: 'English Programme', name_th: 'ป.1A EP', name_en: 'P.1A EP' },
    { id: 'EP1B', program: 'English Programme', name_th: 'ป.1B EP', name_en: 'P.1B EP' },
    { id: 'EP2A', program: 'English Programme', name_th: 'ป.2A EP', name_en: 'P.2A EP' },
    { id: 'EP2B', program: 'English Programme', name_th: 'ป.2B EP', name_en: 'P.2B EP' },
    { id: 'EP3A', program: 'English Programme', name_th: 'ป.3A EP', name_en: 'P.3A EP' },
    { id: 'EP3B', program: 'English Programme', name_th: 'ป.3B EP', name_en: 'P.3B EP' },
    { id: 'EP4A', program: 'English Programme', name_th: 'ป.4A EP', name_en: 'P.4A EP' },
    { id: 'EP4B', program: 'English Programme', name_th: 'ป.4B EP', name_en: 'P.4B EP' },
    { id: 'EP5A', program: 'English Programme', name_th: 'ป.5A EP', name_en: 'P.5A EP' },
    { id: 'EP5B', program: 'English Programme', name_th: 'ป.5B EP', name_en: 'P.5B EP' },
    { id: 'EP6A', program: 'English Programme', name_th: 'ป.6A EP', name_en: 'P.6A EP' },
    { id: 'EP6B', program: 'English Programme', name_th: 'ป.6B EP', name_en: 'P.6B EP' },
    { id: 'EM1A', program: 'English Programme', name_th: 'ม.1A EP', name_en: 'M.1A EP' },
    { id: 'EM1B', program: 'English Programme', name_th: 'ม.1B EP', name_en: 'M.1B EP' },
    { id: 'EM2A', program: 'English Programme', name_th: 'ม.2A EP', name_en: 'M.2A EP' },
    { id: 'EM2B', program: 'English Programme', name_th: 'ม.2B EP', name_en: 'M.2B EP' },
    { id: 'EM3A', program: 'English Programme', name_th: 'ม.3A EP', name_en: 'M.3A EP' },
    { id: 'EM3B', program: 'English Programme', name_th: 'ม.3B EP', name_en: 'M.3B EP' },
    { id: 'EM4A', program: 'English Programme', name_th: 'ม.4A EP', name_en: 'M.4A EP' },
    { id: 'EM5A', program: 'English Programme', name_th: 'ม.5A EP', name_en: 'M.5A EP' },
    { id: 'EM6A', program: 'English Programme', name_th: 'ม.6A EP', name_en: 'M.6A EP' },
];

export const INITIAL_EQUIPMENT: Equipment[] = [
    { id: 'tv', name_th: 'โทรทัศน์ Smart TV', name_en: 'Smart TV' },
    { id: 'remote', name_th: 'รีโมททีวี', name_en: 'TV Remote' },
    { id: 'hdmi', name_th: 'สาย HDMI', name_en: 'HDMI Cable' },
    { id: 'power', name_th: 'สายปลั๊กไฟ', name_en: 'Power Cord' },
    { id: 'stand', name_th: 'ขาตั้งทีวี', name_en: 'TV Stand' },
    { id: 'adapter', name_th: 'อุปกรณ์แปลงสัญญาณ', name_en: 'Signal Adapter' },
];

export const LOCALIZATION = {
  th: {
    // General
    app_title: "ระบบบริหารจัดการ การจอง–ยืม–คืน อุปกรณ์",
    login: "เข้าสู่ระบบ",
    logout: "ออกจากระบบ",
    username: "ชื่อผู้ใช้",
    password: "รหัสผ่าน",
    submit: "ส่งข้อมูล",
    cancel: "ยกเลิก",
    confirm: "ยืนยัน",
    loading: "กำลังโหลด...",
    welcome: "ยินดีต้อนรับ",
    actions: "การดำเนินการ",
    edit: "แก้ไข",
    delete: "ลบ",
    add: "เพิ่ม",
    save: "บันทึก",
    
    // Login
    login_failed: "ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง",
    login_title: "เข้าสู่ระบบ",
    
    // Sidebar
    menu: "เมนู",
    status_view: "ดูสถานะ",
    booking_form: "จอง–ยืมอุปกรณ์",
    return_page: "จัดการการจอง",
    reports: "รายงาน",
    user_management: "จัดการผู้ใช้",
    data_management: "จัดการอุปกรณ์",
    
    // Header
    status_view_title: "ตารางสถานะอุปกรณ์",
    booking_form_title: "แบบฟอร์มจอง-ยืมอุปกรณ์",
    edit_booking_title: "แก้ไขการจอง",
    return_page_title: "จัดการการจอง",
    reports_title: "สร้างรายงาน",
    user_management_title: "จัดการผู้ใช้งาน",
    data_management_title: "จัดการอุปกรณ์",

    // Booking Form
    booking_type: "ประเภท",
    book: "จอง",
    borrow: "ยืม",
    teacher_name: "ชื่อ-สกุลครู",
    program: "โปรแกรม",
    kindergarten: "โปรแกรมอนุบาล",
    classroom: "ห้องเรียน",
    period: "คาบเรียน",
    date: "วันที่ใช้งาน",
    equipment_list: "รายการอุปกรณ์",
    learning_plan: "ชื่อแผนการจัดการเรียนรู้",
    booking_success: "ทำรายการสำเร็จ!",
    booking_update_success: "อัปเดตการจองสำเร็จ!",
    booking_conflict: "มีการจองแล้ว",
    booking_conflict_message: "ห้องเรียน คาบ และวันที่นี้ถูกจองแล้ว",
    form_incomplete: "กรุณากรอกข้อมูลให้ครบถ้วน",
    select_program: "เลือกโปรแกรม",
    select_classroom: "เลือกห้องเรียน",
    select_period: "เลือกคาบ",
    select_equipment: "เลือกอุปกรณ์ (เลือกได้หลายอย่าง)",
    cancellation_success: "ยกเลิกการจองสำเร็จ!",
    cancellation_failed: "ไม่สามารถยกเลิกการจองได้",
    confirm_cancel_prompt: "คุณแน่ใจหรือไม่ว่าต้องการยกเลิกการจองนี้?",
    cancel_booking: "ยกเลิกการจอง",
    delete_booking_success: "ลบการจองสำเร็จ!",


    // Status View
    filter: "ตัวกรอง",
    status: "สถานะ",
    available: "ว่าง",
    booked: "มีการจอง",
    in_use: "กำลังใช้งาน",
    pending_return: "รอคืน",
    not_used: "ไม่มาใช้งาน",
    returned: "คืนแล้ว",
    book_now: "จองเลย",

    // Return Page / Booking Management
    return_confirmation: "ยืนยันการคืน",
    return_success: "บันทึกการคืนสำเร็จ",
    no_items_to_return: "ไม่มีรายการที่ต้องคืน",
    confirm_return_prompt: "คุณต้องการยืนยันการคืนอุปกรณ์สำหรับรายการนี้ใช่หรือไม่?",
    all_statuses: "ทุกสถานะ",

    // Reports
    generate_report: "สร้างรายงาน",
    export_to_excel: "ส่งออกเป็น Excel",
    start_date: "วันที่เริ่มต้น",
    end_date: "วันที่สิ้นสุด",
    report_results: "ผลการรายงาน",
    no_report_data: "ไม่พบข้อมูลตามเงื่อนไขที่เลือก",
    all_teachers: "ครูทั้งหมด",
    all_equipment: "อุปกรณ์ทั้งหมด",
    all_programs: "ทุกโปรแกรม",


    // User Management
    users: "ผู้ใช้งาน",
    add_user: "เพิ่มผู้ใช้ใหม่",
    edit_user: "แก้ไขผู้ใช้",
    user_name: "ชื่อ-สกุล",
    role: "สิทธิ์การใช้งาน",
    teacher: "ครู",
    admin: "ผู้ดูแลระบบ",
    confirm_delete_user: "คุณแน่ใจหรือไม่ว่าต้องการลบผู้ใช้นี้?",
    user_added: "เพิ่มผู้ใช้สำเร็จ",
    user_updated: "อัปเดตผู้ใช้สำเร็จ",
    user_deleted: "ลบผู้ใช้สำเร็จ",

    // Data Management
    classrooms: "ห้องเรียน",
    add_classroom: "เพิ่มห้องเรียน",
    edit_classroom: "แก้ไขห้องเรียน",
    classroom_name_th: "ชื่อห้องเรียน (ไทย)",
    classroom_name_en: "ชื่อห้องเรียน (อังกฤษ)",
    confirm_delete_classroom: "คุณแน่ใจหรือไม่ว่าต้องการลบห้องเรียนนี้?",
    classroom_added: "เพิ่มห้องเรียนสำเร็จ",
    classroom_updated: "อัปเดตห้องเรียนสำเร็จ",
    classroom_deleted: "ลบห้องเรียนสำเร็จ",

    equipment: "อุปกรณ์",
    add_equipment: "เพิ่มอุปกรณ์",
    edit_equipment: "แก้ไขอุปกรณ์",
    equipment_name_th: "ชื่ออุปกรณ์ (ไทย)",
    equipment_name_en: "ชื่ออุปกรณ์ (อังกฤษ)",
    confirm_delete_equipment: "คุณแน่ใจหรือไม่ว่าต้องการลบอุปกรณ์นี้?",
    equipment_added: "เพิ่มอุปกรณ์สำเร็จ",
    equipment_updated: "อัปเดตอุปกรณ์สำเร็จ",
    equipment_deleted: "ลบอุปกรณ์สำเร็จ",

    // Placeholders
    feature_placeholder: 'จะถูกนำมาใช้ในอนาคต',
  },
  en: {
    // General
    app_title: "Equipment Booking & Management System",
    login: "Login",
    logout: "Logout",
    username: "Username",
    password: "Password",
    submit: "Submit",
    cancel: "Cancel",
    confirm: "Confirm",
    loading: "Loading...",
    welcome: "Welcome",
    actions: "Actions",
    edit: "Edit",
    delete: "Delete",
    add: "Add",
    save: "Save",

    // Login
    login_failed: "Invalid username or password",
    login_title: "Login",

    // Sidebar
    menu: "Menu",
    status_view: "Status View",
    booking_form: "Booking Form",
    return_page: "Booking Management",
    reports: "Reports",
    user_management: "User Management",
    data_management: "Equipment Management",

    // Header
    status_view_title: "Equipment Status Timetable",
    booking_form_title: "Equipment Booking Form",
    edit_booking_title: "Edit Booking",
    return_page_title: "Booking Management",
    reports_title: "Report Generation",
    user_management_title: "User Management",
    data_management_title: "Equipment Management",

    // Booking Form
    booking_type: "Type",
    book: "Booking",
    borrow: "Borrow",
    teacher_name: "Teacher's Name",
    program: "Program",
    kindergarten: "Kindergarten Program",
    classroom: "Classroom",
    period: "Period",
    date: "Date of Use",
    equipment_list: "Equipment List",
    learning_plan: "Learning Plan Name",
    booking_success: "Your request has been submitted successfully!",
    booking_update_success: "Booking updated successfully!",
    booking_conflict: "Booking Conflict",
    booking_conflict_message: "This classroom, period, and date is already booked.",
    form_incomplete: "Please fill in all required fields.",
    select_program: "Select a program",
    select_classroom: "Select a classroom",
    select_period: "Select a period",
    select_equipment: "Select equipment (multiple choices allowed)",
    cancellation_success: "Booking cancelled successfully!",
    cancellation_failed: "Could not cancel the booking.",
    confirm_cancel_prompt: "Are you sure you want to cancel this booking?",
    cancel_booking: "Cancel Booking",
    delete_booking_success: "Booking deleted successfully!",

    // Status View
    filter: "Filters",
    status: "Status",
    available: "Available",
    booked: "Booked",
    in_use: "In Use",
    pending_return: "Pending Return",
    not_used: "Not Used",
    returned: "Returned",
    book_now: "Book Now",

    // Return Page / Booking Management
    return_confirmation: "Confirm Return",
    return_success: "Return recorded successfully",
    no_items_to_return: "No items pending return",
    confirm_return_prompt: "Do you want to confirm the return of equipment for this item?",
    all_statuses: "All Statuses",

    // Reports
    generate_report: "Generate Report",
    export_to_excel: "Export to Excel",
    start_date: "Start Date",
    end_date: "End Date",
    report_results: "Report Results",
    no_report_data: "No data found for the selected criteria.",
    all_teachers: "All Teachers",
    all_equipment: "All Equipment",
    all_programs: "All Programs",

    // User Management
    users: "Users",
    add_user: "Add New User",
    edit_user: "Edit User",
    user_name: "Full Name",
    role: "Role",
    teacher: "Teacher",
    admin: "Admin",
    confirm_delete_user: "Are you sure you want to delete this user?",
    user_added: "User added successfully",
    user_updated: "User updated successfully",
    user_deleted: "User deleted successfully",

    // Data Management
    classrooms: "Classrooms",
    add_classroom: "Add Classroom",
    edit_classroom: "Edit Classroom",
    classroom_name_th: "Classroom Name (TH)",
    classroom_name_en: "Classroom Name (EN)",
    confirm_delete_classroom: "Are you sure you want to delete this classroom?",
    classroom_added: "Classroom added successfully",
    classroom_updated: "Classroom updated successfully",
    classroom_deleted: "Classroom deleted successfully",

    equipment: "Equipment",
    add_equipment: "Add Equipment",
    edit_equipment: "Edit Equipment",
    equipment_name_th: "Equipment Name (TH)",
    equipment_name_en: "Equipment Name (EN)",
    confirm_delete_equipment: "Are you sure you want to delete this equipment?",
    equipment_added: "Equipment added successfully",
    equipment_updated: "Equipment updated successfully",
    equipment_deleted: "Equipment deleted successfully",

    // Placeholders
    feature_placeholder: 'feature will be implemented in the future',
  }
};
